#!/bin/bash
xml2po -o mintupdate.pot -m mallard usr/share/help/C/mintupdate/*.page
xgettext --language=Python --keyword=_ --output=mintupdate.pot --join-existing usr/lib/linuxmint/mintUpdate/*.py generate_desktop_files usr/bin/mint-release-upgrade usr/bin/mint-release-upgrade-root usr/lib/linuxmint/mintUpdate/aliases
