#!/bin/sh

sudo rm -rf /usr/lib/linuxmint/mintUpdate
sudo cp -R etc /
sudo cp -R lib/* /lib/
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
sudo gtk-update-icon-cache /usr/share/icons/hicolor
mintupdate
