.\"	Title : mintupdate-launcher
.\"	Author : gm10
.\"	February, 8 2019
.\"
.\" First parameter, NAME, should be all caps
.\" other parameters are allowed: see man(7), man(1)
.TH MINTUPDATE-LAUNCHER 8 "8 February 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" for manpage-specific macros, see man(7)
.SH NAME
mintupdate-launcher \- Linux Mint Update Manager launcher

.SH SYNOPSIS
\fBmintupdate-launcher\fR

.SH DESCRIPTION
\fBmintupdate-launcher\fR launches \fBmintupdate-launcher(8)\fR in tray mode. It is typically being run as a startup application in a user session.

.SH "AUTHOR"
\fBThe Linux Mint developers\fR

.SH SEE ALSO
\fBmintupdate(8)\fR
